repos:
  - repo: local
    hooks:
      - id: ruff-check
        entry: ruff check --force-exclude
        name: ruff check
        require_serial: true
        language: python
        types: [python]
      - id: ruff-format
        name: ruff format
        entry: ruff format --force-exclude
        require_serial: true
        language: python
        types: [python]
